- name: Fetch and run Docker image from Docker Hub
  hosts: localhost
  connection: local
  tasks:
    - name: Pull Docker image from Docker Hub
      docker_image:
        name: "phoenixsac/calcy-repo:latest"
        source: pull

    - name: Run Docker container
      docker_container:
        name: calcy-container
        image: "phoenixsac/calcy-repo:latest"
        state: started
        ports:
           - "8082:8082"
